### PR TITLE
Add SNT

### PR DESCRIPTION
**Pull request by tferr**
(As per https://github.com/morphonets/SNT/issues/39)

### CODE REVIEW

**Comment by tferr** [comment]
Thanks for the speedy merge @ctrueden! BTW, is there anything else we need to do to have snt docs appear on https://javadoc.scijava.org/?

**Comment by imagejan** [comment]
@tferr with this PR, the SNT javadoc is now *integrated* into the Fiji section of javadoc.scijava.org, see:

https://javadoc.scijava.org/Fiji/index.html?tracing/SNT.html

If you want it in a separate section, this PR should be reverted and a new section added in https://github.com/scijava/javadoc.scijava.org. But as SNT is supposed to be part of core Fiji now, I guess it's ok like it is now ?!

**Comment by imagejan** [comment]
I was wrong with my previous comment. The `SNT` class was in the javadoc before already, thanks to the `Simple_Neurite_Tracer` artifact:

https://github.com/fiji/fiji-javadoc/blob/91375079a0e03cb1a12048b7bf54105ffc9c42ba/pom.xml#L330-L333

@tferr with this PR, the build of `fiji-javadoc` is broken now, because there's no `org.morphonets:SNT` artifact deployed to `maven.scijava.org`.

Was your intent to change the name of the artifact from `Simple_Neurite_Tracer` to `SNT`, as for the *repository* names? And what about the `groupId`, should it be `sc.fiji` or `org.morphonets`?

In any case, the following needs to be done to fix the situation:

* Add correct GAV to `pom-scijava`.
* Remove one of `Simple_Neurite_Tracer` or `SNT` in this repository, and change the other one to point to the correct `groupId/artifactId`.

**Comment by tferr** [comment]
@kephale , Pinging you on this.
We do define  `org.morphonets` in the pom, but internally all  packages are defined under the `sc.fiji.` id. Adopting `sc.fiji` throughout would be the least breaking at this point. @kephale , ok with you? What needs to change on sciview-cx3d?

**Comment by kephale** [comment]
I think the groupId should be `org.morphonets`. That simplifies jitpack, it also makes it more coherent than the jungle of projects that are stored under `sc.fiji`, especially because there are a handful of projects under `org.morphonets`.

**Comment by tferr** [comment]
Agree, in retrospect I regret not having changing `sc.fiji` internally while back. OK will do. Will try to tackle this in the pm.

**Comment by tferr** [comment]
@kephale , @imagejan :+1: 
Just to clarify: If we just add the following to [pom.scijava](https://github.com/scijava/pom-scijava), SNT will be automagically available at maven.scijava.org? Is this correct?
```xml
 <dependency> 
 	<groupId>org.morphonets</groupId> 
 	<artifactId>SNT</artifactId> 
 </dependency> 
```
Kyle, how did you manage to have some jitpack versions listed there?

**Comment by kephale** [comment]
@tferr I setup morphonets.org to point to the github organization, so jitpack knows how to find any source with the org.morphonets groupId to build the packages.

@ctrueden setup maven.scijava.org to mirror jitpack. 

Note, I believe that jitpack will even build releases, which would then be mirrored by maven.scijava.org. Otherwise, I believe that the artifacts need to be deployed to maven.scijava.org, which can be done with some pom.xml tricks thanks to the scijava maven plugins. Others know more about the deployment to maven.scijava.org than I do.

**Comment by imagejan** [comment]
@tferr version management in `pom-scijava` and deployment to maven.scijava.org are two different things:
* `pom-scijava` (as a Bill Of Materials) just lists which version of `org.morphonets:SNT` can safely be used with all other components and versions listed in `pom-scijava`.
* Deployment to any Maven repository is handled via continuous integration (currently Travis CI, maybe GitHub actions at some point in the future), and the configuration is contained in the `morphonets/SNT` repository.

`morphonets/SNT` was already set up so that Travis CI will deploy every commit to the `master` branch as current `SNAPSHOT` to maven.scijava.org, and release tags (created by `release-version.sh`) as final releases, but apparently the environment variables don't match the current repository name (any more)?

I tried to fix the issue by re-running `scijava-scripts/travisify.sh` on the repository, and submitted a pull request here:

https://github.com/morphonets/SNT/pull/46

> how did you manage to have some jitpack versions listed there?

As far as I understood, maven.scijava.org is set up as a "lazy" mirror for jitpack, that means any version that once was requested in a POM by *someone* will be cached and listed in the web interface.

**Comment by tferr** [comment]
@imagejan , Thanks a lot for the thorough explanation and for taking the time to run travisify. Travis job is still pending, I the time of this writing, but I think everything is working now. I just realized that there still javadocs being built for legacy projects (e.g., Sholl_Analysis), that are now part of SNT. I will submit a PR for those next.

**Comment by kephale** [comment]
I'll just point out that travis-ci.org is now **wicked** slow. The queue times are frequently >30min and the service is getting shut down this December. The easy solution is transferring to travis-ci.com, which is quite easy but has a limited number of CPU-hours per month.

We migrated sciview to travis-ci.com, but are also setting it up on the Helmholtz GitLab CI infrastructure (which is going through some initial setup now) to ensure that we have unlimited build times. I suspect SNT will be fine of travis-ci.com, but as the Helmholtz infrastructure stabilizes I'd be happy and open to getting SNT and other Morphonets repos setup over there.

**Comment by tferr** [comment]
Yeah, i noticed it is too slow too (maybe it doesn't help, that I commit straight to master all the time :( ). Nice. Good to know.
On an unrelated issue: The javadoc job is still failing. I think this time is because it does not know which [version of SNT to use.](https://travis-ci.org/github/fiji/fiji-javadoc/builds/749324917#L189-L191) I'm guessing this [PR](https://github.com/scijava/pom-scijava/pull/155) will fix things up, correct?

**Comment by tferr** [comment]
Great! then it is all in place with https://github.com/fiji/fiji-javadoc/commit/d53b928f4d046033b99b1b6f35545ce7a0e5810f!

**Comment by ctrueden** [comment]
I pushed a fix to fiji-javadoc that I hope will fix the build for now, until pom-scijava 30.0.0 is released containing the SNT version management.

**Pull request merged**
